USE GuildCars;
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES
   WHERE ROUTINE_NAME = 'GetAllSpecials')
      DROP PROCEDURE GetAllSpecials
GO

CREATE PROCEDURE GetAllSpecials 
AS
	SELECT * FROM Special 
GO